[package]
name = "topic_analyzer"
version = "0.1.0"
authors = ["Mario Mueller <mario@xenji.com>"]

[dependencies]
clap = "~2.29"
env_logger = "~0.5"
log = "~0.4"
prettytable-rs = "0.6.7"
uuid = { version = "0.6.2", features = ["v4"] }
chrono = "0.4"

[dependencies.rdkafka]
version = "~0.15"


[profile.dev]
panic               = 'unwind'
codegen-units       = 2
debug               = true
debug-assertions    = true
lto                 = false
opt-level           = 0
rpath               = false

[profile.release]
codegen-units       = 1
debug               = false
debug-assertions    = false
lto                 = true
opt-level           = 3
rpath               = false

[profile.test]
opt-level           = 0
debug               = true
rpath               = false
lto                 = false
debug-assertions    = true
codegen-units       = 1
panic               = 'unwind'

[profile.bench]
opt-level           = 0
debug               = true
rpath               = false
lto                 = false
debug-assertions    = false
codegen-units       = 1
panic               = 'unwind'
